// Command gendocs renders the gittree command tree as documentation.
//
// It is wired to `make docs` (markdown, committed to docs/) and to
// goreleaser's before hooks (man pages and shell completions, packaged into
// the release archives and installed by the Homebrew cask).
//
//	go run ./tools/gendocs -md docs
//	go run ./tools/gendocs -man man -completions completions
package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/schretzi/gittree/internal/cli"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run() error {
	var mdDir, manDir, compDir string

	flags := newFlagSet(&mdDir, &manDir, &compDir)
	if err := flags.Parse(os.Args[1:]); err != nil {
		return err
	}
	if mdDir == "" && manDir == "" && compDir == "" {
		flags.Usage()
		return errors.New("nothing to do: pass at least one of -md, -man, -completions")
	}

	root := cli.Root()
	// Without this, cobra stamps "Auto generated by spf13/cobra on <date>"
	// into every page, so regenerating churns the whole docs/ directory on
	// every run even when nothing changed.
	root.DisableAutoGenTag = true

	if mdDir != "" {
		if err := writeMarkdown(root, mdDir); err != nil {
			return err
		}
	}
	if manDir != "" {
		if err := writeMan(root, manDir); err != nil {
			return err
		}
	}
	if compDir != "" {
		if err := writeCompletions(root, compDir); err != nil {
			return err
		}
	}
	return nil
}

func writeMarkdown(root *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}
	if err := doc.GenMarkdownTree(root, dir); err != nil {
		return fmt.Errorf("generating markdown: %w", err)
	}
	fmt.Printf("gendocs: wrote markdown to %s/\n", dir)
	return nil
}

func writeMan(root *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}
	header := &doc.GenManHeader{
		Title:   "GITTREE",
		Section: "1",
		Source:  "gittree",
		Manual:  "gittree Manual",
	}
	if err := doc.GenManTree(root, header, dir); err != nil {
		return fmt.Errorf("generating man pages: %w", err)
	}
	fmt.Printf("gendocs: wrote man pages to %s/\n", dir)
	return nil
}

// writeCompletions renders the shell completion scripts cobra generates, so
// they can be shipped in the release archive rather than requiring the user
// to run `gittree completion <shell>` themselves.
func writeCompletions(root *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}

	targets := []struct {
		file string
		gen  func(io.Writer) error
	}{
		{"gittree.bash", func(w io.Writer) error { return root.GenBashCompletionV2(w, true) }},
		{"gittree.zsh", root.GenZshCompletion},
		{"gittree.fish", func(w io.Writer) error { return root.GenFishCompletion(w, true) }},
	}

	for _, t := range targets {
		path := filepath.Join(dir, t.file)
		f, err := os.Create(path) // #nosec G304 -- path is built from a flag this build tool is given
		if err != nil {
			return err
		}
		genErr := t.gen(f)
		closeErr := f.Close()
		if genErr != nil {
			return fmt.Errorf("generating %s: %w", path, genErr)
		}
		if closeErr != nil {
			return fmt.Errorf("closing %s: %w", path, closeErr)
		}
	}
	fmt.Printf("gendocs: wrote completions to %s/\n", dir)
	return nil
}
